[project]
name = "krishna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.18"
dependencies = [
    "meta-ai-api>=1.2.5",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "streamlit>=1.50.0",
    "tensorflow>=2.20.0",
]
